// Browser-side YouTube fallback through public Piped mirrors (they send CORS headers).
// Used only when the primary captions service fails or a video has no captions there.
// Returns caption text (manual or auto-generated) and, when a mirror still serves audio,
// a direct audio URL the on-device transcriber can use.

export interface MirrorCaptions {
  transcript: string;
  timestampedTranscript: string;
}

export interface MirrorResult {
  captions: MirrorCaptions | null;
  audioUrl: string | null;
  title?: string;
  instance: string;
}

interface PipedSubtitle {
  url: string;
  mimeType?: string;
  name?: string;
  code?: string;
  autoGenerated?: boolean;
}

interface PipedStreams {
  title?: string;
  subtitles?: PipedSubtitle[];
  audioStreams?: { url: string; mimeType?: string; bitrate?: number; format?: string }[];
}

// Known-good first; the live list from Piped's docs is merged in at runtime.
const STATIC_INSTANCES = [
  "https://api.piped.private.coffee",
  "https://pipedapi.kavin.rocks",
  "https://api.piped.yt",
  "https://pipedapi.adminforge.de",
  "https://pipedapi.drgns.space",
  "https://pipedapi.r4fo.com",
  "https://api.piped.projectsegfau.lt",
];

const INSTANCE_LIST_URL =
  "https://raw.githubusercontent.com/TeamPiped/documentation/main/content/docs/public-instances/index.md";

async function fetchWithTimeout(url: string, ms: number, init: RequestInit = {}): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), ms);
  try {
    return await fetch(url, { ...init, signal: controller.signal, referrerPolicy: "no-referrer" });
  } finally {
    clearTimeout(timer);
  }
}

let instancesPromise: Promise<string[]> | null = null;

export function listInstances(): Promise<string[]> {
  if (!instancesPromise) {
    instancesPromise = (async () => {
      const found: string[] = [];
      try {
        const md = await (await fetchWithTimeout(INSTANCE_LIST_URL, 6000)).text();
        for (const m of md.matchAll(/https:\/\/[a-z0-9.-]+/gi)) {
          const u = m[0].replace(/\/+$/, "");
          if (/api/i.test(u) && /piped/i.test(u)) found.push(u);
        }
      } catch {
        /* offline list is fine */
      }
      return Array.from(new Set([...STATIC_INSTANCES, ...found]));
    })();
  }
  return instancesPromise;
}

const clock = (s: number) => {
  const t = Math.max(0, Math.floor(s));
  const h = Math.floor(t / 3600);
  const m = Math.floor((t % 3600) / 60);
  const sec = t % 60;
  return h > 0 ? `${h}:${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")}` : `${m}:${String(sec).padStart(2, "0")}`;
};

function parseVttTime(t: string): number | null {
  const m = t.trim().match(/^(?:(\d+):)?(\d{1,2}):(\d{2})(?:[.,](\d{1,3}))?$/);
  if (!m) return null;
  const h = m[1] ? Number(m[1]) : 0;
  return h * 3600 + Number(m[2]) * 60 + Number(m[3]) + (m[4] ? Number(m[4].padEnd(3, "0")) / 1000 : 0);
}

const stripTags = (s: string) =>
  s
    .replace(/<[^>]+>/g, "")
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, " ")
    .trim();

/** Parse WebVTT (including YouTube's rolling auto-caption style) into de-duplicated cues. */
export function parseVtt(vtt: string): { start: number; text: string }[] {
  const cues: { start: number; text: string }[] = [];
  const blocks = vtt.replace(/\r/g, "").split(/\n\n+/);
  let previous = "";
  for (const block of blocks) {
    const lines = block.split("\n").filter((l) => l.trim());
    const idx = lines.findIndex((l) => l.includes("-->"));
    if (idx === -1) continue;
    const start = parseVttTime(lines[idx].split("-->")[0]);
    if (start === null) continue;
    let text = stripTags(lines.slice(idx + 1).join(" "));
    if (!text) continue;
    // YouTube auto captions repeat the previous line before the new one — keep only the new part.
    if (previous && text.startsWith(previous)) text = text.slice(previous.length).trim();
    if (!text || text === previous) continue;
    cues.push({ start, text });
    previous = text;
  }
  return cues;
}

function parseTtmlTime(t: string): number | null {
  const clockMatch = t.trim().match(/^(?:(\d+):)?(\d{1,2}):(\d{2})(?:[.,](\d{1,3}))?$/);
  if (clockMatch) return parseVttTime(t);
  const unit = t.trim().match(/^([\d.]+)(ms|s)$/);
  if (unit) return unit[2] === "ms" ? Number(unit[1]) / 1000 : Number(unit[1]);
  return null;
}

/** Parse TTML (what YouTube's timedtext returns for fmt=ttml) into de-duplicated cues. */
export function parseTtml(xml: string): { start: number; text: string }[] {
  const cues: { start: number; text: string }[] = [];
  let previous = "";
  for (const m of xml.matchAll(/<p\b([^>]*)>([\s\S]*?)<\/p>/gi)) {
    const begin = m[1].match(/begin="([^"]+)"/)?.[1];
    if (!begin) continue;
    const start = parseTtmlTime(begin);
    if (start === null) continue;
    let text = stripTags(m[2].replace(/<br\s*\/?>/gi, " "));
    if (!text) continue;
    if (previous && text.startsWith(previous)) text = text.slice(previous.length).trim();
    if (!text || text === previous) continue;
    cues.push({ start, text });
    previous = text;
  }
  return cues;
}

/** Detect the caption format and parse it. */
export function parseCaptionTrack(body: string): { start: number; text: string }[] {
  const head = body.slice(0, 500);
  if (/<tt[\s>]|<p\b[^>]*begin=/i.test(head) || /^\s*<\?xml/.test(head)) return parseTtml(body);
  return parseVtt(body);
}

export function cuesToCaptions(cues: { start: number; text: string }[]): MirrorCaptions | null {
  if (cues.length === 0) return null;
  const transcript = cues
    .map((c) => c.text)
    .join(" ")
    .replace(/\s+/g, " ")
    .replace(/([.!?])\s+/g, "$1\n\n")
    .trim();
  return { transcript, timestampedTranscript: cues.map((c) => `[${clock(c.start)}] ${c.text}`).join("\n") };
}

function pickSubtitle(subs: PipedSubtitle[], language: string): PipedSubtitle | null {
  const lang = language.toLowerCase();
  const matches = (s: PipedSubtitle) => (s.code ?? "").toLowerCase().split("-")[0] === lang;
  return (
    subs.find((s) => matches(s) && !s.autoGenerated) ??
    subs.find((s) => matches(s)) ??
    subs.find((s) => (s.code ?? "").toLowerCase().startsWith("en") && !s.autoGenerated) ??
    subs.find((s) => (s.code ?? "").toLowerCase().startsWith("en")) ??
    subs[0] ??
    null
  );
}

async function queryInstance(instance: string, videoId: string, language: string): Promise<MirrorResult> {
  const res = await fetchWithTimeout(`${instance}/streams/${videoId}`, 9000);
  if (!res.ok) throw new Error(`${instance} ${res.status}`);
  const data = (await res.json()) as PipedStreams;

  let captions: MirrorCaptions | null = null;
  const sub = pickSubtitle(data.subtitles ?? [], language);
  if (sub?.url) {
    const track = await fetchWithTimeout(sub.url, 9000);
    if (track.ok) captions = cuesToCaptions(parseCaptionTrack(await track.text()));
  }

  const audio = (data.audioStreams ?? [])
    .filter((a) => a.url && /audio\/(mp4|m4a)/i.test(a.mimeType ?? "") )
    .sort((a, b) => (a.bitrate ?? 0) - (b.bitrate ?? 0))[0];

  if (!captions && !audio) throw new Error(`${instance}: no captions or audio`);
  return { captions, audioUrl: audio?.url ?? null, title: data.title, instance };
}

/** Resolves with the first fulfilled promise, or null once every attempt has failed. */
function firstFulfilled<T>(attempts: Promise<T>[]): Promise<T | null> {
  if (attempts.length === 0) return Promise.resolve(null);
  return new Promise((resolve) => {
    let pending = attempts.length;
    for (const attempt of attempts) {
      attempt.then(
        (value) => resolve(value),
        () => {
          pending -= 1;
          if (pending === 0) resolve(null);
        },
      );
    }
  });
}

/** Race the mirrors; the first one that yields captions or audio wins. */
export async function fetchYouTubeFromMirrors(videoId: string, language = "en"): Promise<MirrorResult | null> {
  const instances = await listInstances();
  return firstFulfilled(instances.slice(0, 8).map((i) => queryInstance(i, videoId, language)));
}
